# General
RESOLUTION = (320, 240)
TARGET_FPS = 60
SHOW_FPS = True
LEVELS = ["tutorial", "level2"]

# Gameplay
GRIDSIZE = 16
SNAKE_MOVE_INTERVAL = 0.9  # in seconds
GRAVSTRENGTH = 100
SNAKECHARMER_MOVE_SPEED = 2.5  # in grid-squares/second
SNAKECHARMER_JUMP_FORCE = 3000
