RESOLUTION = (320, 240)
TARGET_FPS = 60
GRIDSIZE = 16
SNAKE_MOVE_INTERVAL = 0.9  # in seconds
SHOW_FPS = True
GRAVSTRENGTH = 50
SNAKECHARMER_MOVE_SPEED = 2  # in grid-squares/second
SNAKECHARMER_JUMP_FORCE = 1000
